services:
  app:
    build: ./app
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/app
    command: ng serve --host 0.0.0.0

  db:
    image: mysql:latest
    restart: always
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./server:/server
    command: deno run -A dev